#!/usr/bin/env bash

# Base paramters, X11 parameters
BPRM="--rm -it --network=host -v $HOME:$HOME -v/dev/bus/:/dev/bus -w $PWD --privileged -e XDEV=dev-$1"
XPRM="-v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:$HOME/.Xauthority -e DISPLAY=$DISPLAY"
SPRM="-v $XDG_RUNTIME_DIR/pulse:/tmp/pulse"

# Get env name and remove it from $@
env=$1
shift

xhost +local:docker >>/dev/null
docker run $BPRM $XPRM $SPRM dev-$env $@
